### ISSUE TITLE
[IMPROVE] Table of Contents on the side

### ISSUE THREAD

**Issue by MesterMan03** [noClaps/blog#79]
### Have you read the code of conduct?

- [X] I have read the code of conduct.

### Has this improvement already been suggested?

- [X] My improvement has not been suggested yet.

### Package

blog

### Where can I improve?

It'd be really nice if you didn't have to scroll up every time for the ToC, but instead it was always there on the left side of the screen.

**Comment by noClaps** [comment]
Due to the current layout of the post pages, there's simply not enough room to fit in a table of contents section on each post page. There's a Back to Top button for this reason as scrolling back up can be tedious, especially with longer posts.

Also, a table of contents on the side would conflict with the mobile view, and I'd have to design a sidebar or similar implementation for it.

I'll leave this issue open for the future, but there's currently no plans to add this feature.
